import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { McLaren,Comfortaa } from "next/font/google";
import SessionProvider from "@/components/auth/CustomSessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const mclaren = McLaren({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-mclaren',
});

const roboto= Roboto({
  subsets:['latin'],
  variable:'--font-roboto'
})

const comfortaa = Comfortaa({
  subsets: ['latin'],
  variable: '--font-comfortaa',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mclaren.variable} ${comfortaa.variable}  ${roboto.variable} flex flex-col antialiased`}
      >
        <SessionProvider>
        
        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
